name = "Adrenaline"
author = "UltraStorm"
version = "1.12.3+1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5e635cd56565cac2be2f98e8bf6841821e868d41ccf4f3aa24668f2590350e2"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"
