name = "Bepic Create"
author = "BattleCh1cken"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "796dd804e5c62e561190f463c394ecbac57e82ce7e54c1f27ce58efe0e2889dc"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
