name = "idk stuff"
author = "BattleCh1cken"
version = "1.12.3+1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c40dda387fda5ff18ec89eab05a4c9dc7b135d13aad31f8a1ce88204799b0af"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2", "1.19.1", "1.19"]
datapack-folder = "datapacks"
