name = "Bepic Create"
author = "BattleCh1cken"
version = "1.16.2+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16d2874ba0e64cab330d950618953d360edcdf6f0cf921628c41aacc29ad65c0"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
