name = "Bepic Create"
author = "BattleCh1cken"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a7e9b7aa2904079b2ebf7d4d5f0c645d3d2a0ce1655ecb9249c16a394d25863"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
