name = "Bepic Create"
author = "BattleCh1cken"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaf12243d475af215d75d7e0932c7e1cba449fda3ba132d84bbbf47dd0acb881"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
