name = "Bepic Create"
author = "BattleCh1cken"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dee1c00d95e2115f90979d3a08f5a2361ddcfa68e0396099994d004544fe0360"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
