name = "Bepic Create"
author = "BattleCh1cken"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3c1d9eef8f1398ac1203ceaf00721a4944467ea1d45fb2a9d8e21ef08758f04"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
